tasks:
  - name: infra
    before: cd infra
    init: |
      npm install
    command: |
      npm run build
  - name: cli
    before: cd cli
    init: |
      npm install -g && npm run build && npm install -g esbuild   
  - name: jvm
    before: cd lib/java/matano 
    init: |
      gradle build
  - name: vector
    before: cd lambdas/vrl-transform-bindings
    init: |
      git clone https://github.com/vectordotdev/vector.git
image:
  file: .gitpod.Dockerfile

jetbrains:
  intellij:
    prebuilds:
      version: stable