tasks:
  - name: infra
    before: cd infra
    init: |
      npm install
    command: |
      npm run build
  - name: cli
    before: cd cli
    init: |
      npm run full-install
  - name: jvm
    before: cd lib/java/matano 
    init: |
      gradle build
  - name: rust
    before: cd lib/java/rust
    init: |
      cargo build
image:
  file: .gitpod.Dockerfile

jetbrains:
  intellij:
    prebuilds:
      version: stable