name: 'nightly-release'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Clone repository
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    # Build your application, tool, artifacts, etc.
    - name: Build
      shell: bash
      run: |
        make package

    - uses: actions/upload-artifact@v3
      with:
        name: build-assets
        path: matano*.sh

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: actions/download-artifact@v3
      with:
        name: build-assets

    - name: "Update nightly release"
      if: success()
      uses: pyTooling/Actions/releaser@r0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        files: |
          matano*.sh
